var searchData=
[
  ['handling_0',['Handling',['../index.html#modbus-errors',1,'2.5 Error Handling'],['../index.html#autotoc_md168',1,'Exception Handling']]],
  ['happens_20at_20startup_1',['What Happens at Startup',['../index.html#startup',1,'']]],
  ['hardware_2',['ESP32 Hardware',['../index.html#autotoc_md13',1,'']]],
  ['hardware_3',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['hardware_20does_20lamblisp_20run_20on_4',['What hardware does LambLisp run on?',['../index.html#autotoc_md173',1,'']]],
  ['hardware_20platform_20builtins_20xmop3_5',['Hardware &amp;amp; Platform Builtins (xmop3)',['../group__xmop3.html',1,'']]],
  ['hardware_20setup_6',['2. Hardware Setup',['../index.html#fwd-hw',1,'']]],
  ['has_20a_20socket_20must_20now_20say_20so_7',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['hash_8',['hash',['../classCell.html#af95a9dc7e5358327e79928fa1f55ff30',1,'Cell']]],
  ['hash_20table_20and_20hashing_20details_9',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['hash_20table_20sizing_20and_20collisions_10',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['hash_5fcontents_11',['hash_contents',['../classCell.html#ac8e26e947293f804f03852ae1997a378',1,'Cell']]],
  ['hash_5fsexpr_12',['hash_sexpr',['../classCell.html#ad719b3adde9c9196d59d69986fdbfdeb',1,'Cell']]],
  ['hashing_20details_13',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['have_20three_20states_14',['Which ports have three states',['../index.html#autotoc_md164',1,'']]],
  ['hc_20sr04_15',['HC SR04',['../group__xmop3__sonar.html',1,'Ultrasonic Sonar (HC-SR04)'],['../index.html#ultrasonic-sonar-hc-sr04',1,'Ultrasonic Sonar (HC-SR04)']]],
  ['helpers_16',['2.4 Float32 Helpers',['../index.html#modbus-float32',1,'']]],
  ['hierarchical_20dictionaries_17',['Hierarchical dictionaries',['../index.html#arch-hierdict',1,'']]],
  ['hierarchical_20dictionaries_18',['hierarchical dictionaries',['../index.html#autotoc_md25',1,'First-class hierarchical dictionaries'],['../index.html#autotoc_md34',1,'Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;']]],
  ['hierarchical_20dictionary_19',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['hip_20rocm_20gpu_20',['HIP / ROCm GPU',['../group__xmop3__hip.html',1,'']]],
  ['hip_5finstall_5fmop3_21',['Hip_install_mop3',['../group__xmop3__hip.html#ga8fbf06e984eeb88888602efc094b2f75',1,'ll_xmop3_Hip.cu']]],
  ['history_20of_20lisp_20and_20scheme_22',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['host_20compatibility_23',['A note on host compatibility',['../index.html#autotoc_md11',1,'']]],
  ['hot_20reload_24',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['hot_20reload_20without_20reboot_25',['Hot-Reload Without Reboot',['../index.html#llip-hotreload',1,'']]],
  ['how_20blocking_20works_20on_20a_20port_26',['How blocking works on a port',['../index.html#port-blocking',1,'']]],
  ['how_20do_20i_20try_20lamblisp_20right_20now_27',['How do I try LambLisp right now?',['../index.html#autotoc_md171',1,'']]],
  ['how_20do_20i_20update_20code_20without_20reflashing_28',['How do I update code without reflashing?',['../index.html#autotoc_md177',1,'']]],
  ['how_20fast_20is_20lamblisp_29',['How fast is LambLisp?',['../index.html#autotoc_md184',1,'']]],
  ['http_20llm_20layer_20llip_20http_20scm_30',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['http_20scm_31',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['hygiene_32',['Hygiene',['../index.html#autotoc_md57',1,'']]]
];
