var searchData=
[
  ['handling_0',['Handling',['../index.html#modbus-errors',1,'2.5 Error Handling'],['../index.html#autotoc_md168',1,'Exception Handling']]],
  ['happens_20at_20startup_1',['What Happens at Startup',['../index.html#startup',1,'']]],
  ['hardware_2',['ESP32 Hardware',['../index.html#autotoc_md13',1,'']]],
  ['hardware_3',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['hardware_20does_20lamblisp_20run_20on_4',['What hardware does LambLisp run on?',['../index.html#autotoc_md173',1,'']]],
  ['hardware_20setup_5',['2. Hardware Setup',['../index.html#fwd-hw',1,'']]],
  ['has_20a_20socket_20must_20now_20say_20so_6',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['hash_20table_20and_20hashing_20details_7',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['hash_20table_20sizing_20and_20collisions_8',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['hashing_20details_9',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['have_20three_20states_10',['Which ports have three states',['../index.html#autotoc_md164',1,'']]],
  ['hc_20sr04_11',['Ultrasonic Sonar (HC-SR04)',['../index.html#ultrasonic-sonar-hc-sr04',1,'']]],
  ['helpers_12',['2.4 Float32 Helpers',['../index.html#modbus-float32',1,'']]],
  ['hierarchical_20dictionaries_13',['Hierarchical dictionaries',['../index.html#arch-hierdict',1,'']]],
  ['hierarchical_20dictionaries_14',['hierarchical dictionaries',['../index.html#autotoc_md25',1,'First-class hierarchical dictionaries'],['../index.html#autotoc_md34',1,'Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;']]],
  ['hierarchical_20dictionary_15',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['history_20of_20lisp_20and_20scheme_16',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['host_20compatibility_17',['A note on host compatibility',['../index.html#autotoc_md11',1,'']]],
  ['hot_20reload_18',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['hot_20reload_20without_20reboot_19',['Hot-Reload Without Reboot',['../index.html#llip-hotreload',1,'']]],
  ['how_20blocking_20works_20on_20a_20port_20',['How blocking works on a port',['../index.html#port-blocking',1,'']]],
  ['how_20do_20i_20try_20lamblisp_20right_20now_21',['How do I try LambLisp right now?',['../index.html#autotoc_md171',1,'']]],
  ['how_20do_20i_20update_20code_20without_20reflashing_22',['How do I update code without reflashing?',['../index.html#autotoc_md177',1,'']]],
  ['how_20fast_20is_20lamblisp_23',['How fast is LambLisp?',['../index.html#autotoc_md184',1,'']]],
  ['http_20llm_20layer_20llip_20http_20scm_24',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['http_20scm_25',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['hygiene_26',['Hygiene',['../index.html#autotoc_md57',1,'']]]
];
