var searchData=
[
  ['machine_0',['Machine',['../index.html#autotoc_md48',1,'AI and Machine-to-Machine'],['../index.html#arch-bc',1,'Bytecode Virtual Machine'],['../index.html#autotoc_md36',1,'LambLisp Virtual Machine']]],
  ['machine_20to_20machine_1',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['machines_2',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['macro_3',['macro',['../index.html#arch-lambda',1,'lambda, nlambda, and macro'],['../index.html#autotoc_md56',1,'macro']]],
  ['macro_20cannot_20enforce_4',['Two rules the macro cannot enforce',['../index.html#autotoc_md66',1,'']]],
  ['making_20it_20yours_5',['Making it yours',['../index.html#package-customize',1,'']]],
  ['management_6',['Memory Management',['../index.html#autotoc_md39',1,'']]],
  ['map_7',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['map_20accumulator_20floor_20map_20scm_8',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['map_20scm_9',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['map_20store_20and_20ascii_20render_10',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['mapping_20demo_20telemetry_20scm_11',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md124',1,'']]],
  ['mapping_20with_20the_20freenove_204wd_20car_12',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['marshaling_13',['Data Marshaling',['../index.html#autotoc_md73',1,'']]],
  ['master_14',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['master_15',['PROFIBUS DP master',['../index.html#autotoc_md118',1,'']]],
  ['math_20linear_20algebra_16',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['matrix_17',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['may_20contain_20nul_20and_20string_20length_20is_20the_20authority_18',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['meaning_20of_200_19',['The bulk form, and the meaning of &lt;span class=&quot;tt&quot;&gt;0&lt;/span&gt;',['../index.html#autotoc_md161',1,'']]],
  ['means_20has_20a_20socket_20must_20now_20say_20so_20',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['memory_20and_20gc_20tuning_21',['Memory and GC Tuning',['../index.html#arch-adaptive',1,'']]],
  ['memory_20and_20pre_20reserve_22',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['memory_20footprint_23',['What is the memory footprint?',['../index.html#autotoc_md208',1,'']]],
  ['memory_20management_24',['Memory Management',['../index.html#autotoc_md39',1,'']]],
  ['memory_20model_20and_20list_20structures_25',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['memory_20tuning_26',['GC and memory tuning',['../index.html#autotoc_md84',1,'']]],
  ['memory_20tuning_3a_20stack_20size_20dma_20memory_20and_20pre_20reserve_27',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['micro_20controllers_28',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['microprocessors_29',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['microsecond_20isr_30',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md44',1,'']]],
  ['modbus_20controller_31',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['modbus_20interface_32',['LambLisp Modbus Interface',['../index.html#modbus',1,'']]],
  ['modbus_20peripheral_33',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['modbus_20request_34',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]],
  ['model_35',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['model_36',['model',['../index.html#profinet-device-model',1,'5.3 Device model'],['../index.html#autotoc_md80',1,'The boot-confirm / rollback model']]],
  ['model_20and_20list_20structures_37',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['module_38',['3.5 Bee Strategy Module',['../index.html#fwd-bee-onboard',1,'']]],
  ['motion_20primitives_39',['3.2 Motion Primitives',['../index.html#fwd-motion',1,'']]],
  ['motors_20pca9685_20scm_40',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md103',1,'']]],
  ['multi_20platform_41',['Multi-platform',['../index.html#autotoc_md20',1,'']]],
  ['multi_20platform_20support_42',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['music_20scm_43',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md125',1,'']]],
  ['musical_20notes_20music_20scm_44',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md125',1,'']]],
  ['must_20now_20say_20so_45',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]]
];
