var searchData=
[
  ['lambda_0',['lambda',['../index.html#autotoc_md54',1,'']]],
  ['lambda_20nlambda_20and_20macro_1',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['lamblisp_2',['LambLisp',['../index.html#autotoc_md1',1,'Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;'],['../index.html#autotoc_md184',1,'How fast is LambLisp?'],['../index.html#why-lamblisp',1,'Why &lt;em&gt;LambLisp&lt;/em&gt;?']]],
  ['lamblisp_20architecture_20internals_3',['LambLisp Architecture Internals',['../index.html#autotoc_md32',1,'']]],
  ['lamblisp_20as_20modbus_20controller_4',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['lamblisp_20as_20modbus_20peripheral_5',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['lamblisp_20bacnet_20ip_20interface_6',['LambLisp BACnet/IP Interface',['../index.html#bacnet',1,'']]],
  ['lamblisp_20block_20diagram_7',['LambLisp Block Diagram',['../index.html#autotoc_md38',1,'']]],
  ['lamblisp_20compatibility_20matrix_8',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['lamblisp_20extensions_9',['LambLisp Extensions',['../index.html#autotoc_md74',1,'']]],
  ['lamblisp_20frequently_20asked_20questions_10',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['lamblisp_20in_20a_20container_11',['Running LambLisp in a Container',['../index.html#containers',1,'']]],
  ['lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_12',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['lamblisp_20in_20your_20browser_13',['Quick Start: Try LambLisp in Your Browser',['../index.html#quick-start-browser',1,'']]],
  ['lamblisp_20instead_20of_20scheme_14',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md191',1,'']]],
  ['lamblisp_20interaction_20protocol_15',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['lamblisp_20interoperate_20with_20c_20c_20code_16',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md204',1,'']]],
  ['lamblisp_20modbus_20interface_17',['LambLisp Modbus Interface',['../index.html#modbus',1,'']]],
  ['lamblisp_20on_20linux_18',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['lamblisp_20on_20windows_19',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['lamblisp_20open_20source_20',['Is LambLisp open source?',['../index.html#autotoc_md175',1,'']]],
  ['lamblisp_20profibus_20and_20profinet_20interface_21',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['lamblisp_20right_20now_22',['How do I try LambLisp right now?',['../index.html#autotoc_md171',1,'']]],
  ['lamblisp_20run_20on_23',['What hardware does LambLisp run on?',['../index.html#autotoc_md173',1,'']]],
  ['lamblisp_20sit_20in_20the_20lisp_20landscape_24',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md195',1,'']]],
  ['lamblisp_20virtual_20machine_25',['LambLisp Virtual Machine',['../index.html#autotoc_md36',1,'']]],
  ['lamblisp_20without_20an_20rtos_26',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md206',1,'']]],
  ['lamblisp_3a_20the_20full_20image_27',['Building your own &lt;em&gt;LambLisp&lt;/em&gt;: the &lt;span class=&quot;tt&quot;&gt;full&lt;/span&gt; image',['../index.html#container-full',1,'']]],
  ['landscape_28',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md195',1,'']]],
  ['language_29',['Core Language',['../index.html#autotoc_md132',1,'']]],
  ['language_30',['Try the language',['../index.html#autotoc_md7',1,'']]],
  ['language_20and_20conformance_31',['Language and Conformance',['../index.html#autotoc_md190',1,'']]],
  ['language_20extensions_32',['Language Extensions',['../index.html#language-extensions',1,'']]],
  ['language_20internals_20and_20c_20api_33',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['language_20specification_34',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md21',1,'']]],
  ['latency_20—_20no_20stop_20the_20world_20pauses_35',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['latency_20—_20sub_20microsecond_20isr_36',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md44',1,'']]],
  ['layer_37',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]],
  ['layer_20llip_20http_20scm_38',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['lcd_20primitives_20c_39',['Camera / LCD primitives (C++)',['../index.html#autotoc_md101',1,'']]],
  ['lcd1602_20display_40',['LCD1602 Display',['../index.html#autotoc_md97',1,'']]],
  ['led_20ring_20service_20leds_20scm_41',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['led_20strip_20neopixel_42',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md99',1,'']]],
  ['leds_20scm_43',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['leds_20ws2812_20scm_44',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md104',1,'']]],
  ['legend_45',['Legend',['../index.html#autotoc_md127',1,'']]],
  ['length_20is_20the_20authority_46',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['lexical_20scoping_47',['Lexical scoping',['../index.html#autotoc_md27',1,'']]],
  ['libgpiod_48',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['libraries_49',['Bundled Scheme Libraries',['../index.html#scheme-libraries',1,'']]],
  ['libraries_50',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['license_51',['License',['../index.html#license',1,'']]],
  ['lifecycle_52',['Connection Lifecycle',['../index.html#autotoc_md87',1,'']]],
  ['lifecycle_3a_20incremental_20hot_20reload_53',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['light_20sensor_20lightsensor_20scm_54',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md109',1,'']]],
  ['lightsensor_20scm_55',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md109',1,'']]],
  ['lightweight_20object_20system_56',['Lightweight object system',['../index.html#autotoc_md62',1,'']]],
  ['like_20when_20you_20get_20it_20wrong_57',['What it looks like when you get it wrong',['../index.html#autotoc_md68',1,'']]],
  ['limits_58',['5. Requirements and limits',['../index.html#bacnet-limits',1,'']]],
  ['line_20client_3a_20tools_20llip_59',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['linear_20algebra_60',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['linux_61',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['linux_20and_20what_20is_20not_62',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['linux_20jetson_20builds_63',['Linux / Jetson Builds',['../index.html#autotoc_md14',1,'']]],
  ['linux_20x86_5f64_20and_20aarch64_64',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['lisp_65',['Why Lisp?',['../index.html#autotoc_md18',1,'']]],
  ['lisp_20and_20scheme_66',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['lisp_20for_20microprocessors_67',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['lisp_20in_20a_20nutshell_68',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md17',1,'']]],
  ['lisp_20landscape_69',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md195',1,'']]],
  ['lisp_20primitives_70',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#open-api',1,'']]],
  ['list_20structures_71',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['lists_72',['Pairs and Lists',['../index.html#autotoc_md142',1,'']]],
  ['live_20preview_20layer_73',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]],
  ['llip_74',['What is LLIP?',['../index.html#autotoc_md182',1,'']]],
  ['llip_75',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['llip_20—_20lamblisp_20interaction_20protocol_76',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['llip_20as_20the_20universal_20glue_77',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['llip_20client_20scm_78',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md90',1,'']]],
  ['llip_20http_20scm_79',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['llip_20serial_20scm_80',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['llip_20server_20scm_81',['Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)',['../index.html#autotoc_md91',1,'']]],
  ['llip_20transport_20scm_82',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['llm_20layer_20llip_20http_20scm_83',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['llvm_20for_20native_20code_20generation_84',['Why not use LLVM for native code generation?',['../index.html#autotoc_md199',1,'']]],
  ['loader_20wire_20contract_20nvs_85',['The loader wire contract (NVS)',['../index.html#autotoc_md79',1,'']]],
  ['looks_20like_20when_20you_20get_20it_20wrong_86',['What it looks like when you get it wrong',['../index.html#autotoc_md68',1,'']]],
  ['loop_87',['Loop',['../index.html#profibus-loop',1,'2.3 The Service Loop'],['../index.html#modbus-serve-loop',1,'3.4 The Serve Loop']]],
  ['loop_20time_20—_20bounded_20control_20cycle_88',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md43',1,'']]]
];
