var searchData=
[
  ['naming_0',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['native_20code_1',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['native_20code_20generation_2',['Why not use LLVM for native code generation?',['../index.html#autotoc_md199',1,'']]],
  ['native_20code_20generator_20ncg_3',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['navigation_4',['3.4 Waypoint Navigation',['../index.html#fwd-nav',1,'']]],
  ['ncg_5',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['ncg_20compilation_6',['What is bytecode / NCG compilation?',['../index.html#autotoc_md186',1,'']]],
  ['need_7',['What you need',['../index.html#autotoc_md2',1,'']]],
  ['needs_20protecting_8',['What needs protecting',['../index.html#autotoc_md65',1,'']]],
  ['neopixel_9',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md99',1,'']]],
  ['network_20reach_10',['Network Reach',['../index.html#autotoc_md47',1,'']]],
  ['network_20time_20sntp_11',['Network Time (SNTP)',['../index.html#nettime',1,'']]],
  ['new_20lisp_20primitives_12',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#open-api',1,'']]],
  ['nlambda_13',['nlambda',['../index.html#autotoc_md55',1,'']]],
  ['nlambda_20and_20macro_14',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['no_20stop_20the_20world_20pauses_15',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['non_20blocking_20request_20poll_20model_16',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['non_20symbol_20keys_17',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['not_18',['not',['../index.html#autotoc_md8',1,'What is in the image, and what is not'],['../index.html#autotoc_md6',1,'What is the same as Linux, and what is not']]],
  ['not_20exceptions_19',['2.4 Events, Not Exceptions',['../index.html#profibus-events',1,'']]],
  ['not_20run_20on_20embedded_20hardware_20',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['not_20the_20same_20thing_21',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['not_20use_20embedded_20python_20derivatives_22',['Why not use embedded Python derivatives?',['../index.html#autotoc_md197',1,'']]],
  ['not_20use_20llvm_20for_20native_20code_20generation_23',['Why not use LLVM for native code generation?',['../index.html#autotoc_md199',1,'']]],
  ['not_20work_24',['When it does not work',['../index.html#package-troubleshooting',1,'']]],
  ['note_20on_20host_20compatibility_25',['A note on host compatibility',['../index.html#autotoc_md11',1,'']]],
  ['notes_26',['Notes',['../index.html#modbus-platform',1,'4. Platform Notes'],['../index.html#fwd-arch-notes',1,'7. Architecture Notes']]],
  ['notes_20music_20scm_27',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md125',1,'']]],
  ['now_28',['How do I try LambLisp right now?',['../index.html#autotoc_md171',1,'']]],
  ['now_20say_20so_29',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['nul_20and_20string_20length_20is_20the_20authority_30',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['numbers_31',['Numbers',['../index.html#autotoc_md138',1,'']]],
  ['numeric_20arrays_20array_32',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['numeric_20tower_33',['The Numeric Tower',['../index.html#autotoc_md136',1,'']]],
  ['nutshell_34',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md17',1,'']]],
  ['nvs_35',['The loader wire contract (NVS)',['../index.html#autotoc_md79',1,'']]]
];
