var searchData=
[
  ['a_20—_20reach_0',['Group A — Reach',['../index.html#autotoc_md46',1,'']]],
  ['a_20container_1',['Running LambLisp in a Container',['../index.html#containers',1,'']]],
  ['a_20container_2',['Flashing from a container',['../index.html#flashing-from-a-container',1,'']]],
  ['a_20coverage_20plan_3',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['a_20device_20object_4',['4. Answering as a Device object',['../index.html#bacnet-device',1,'']]],
  ['a_20guard_20that_20means_20has_20a_20socket_20must_20now_20say_20so_5',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['a_20hierarchical_20dictionary_6',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['a_20jetson_20or_20raspberry_20pi_20libgpiod_7',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['a_20master_8',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['a_20note_20on_20host_20compatibility_9',['A note on host compatibility',['../index.html#autotoc_md11',1,'']]],
  ['a_20nutshell_10',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md17',1,'']]],
  ['a_20peripheral_11',['3.1 Opening a Peripheral',['../index.html#modbus-peripheral-open',1,'']]],
  ['a_20pin_12',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['a_20port_13',['How blocking works on a port',['../index.html#port-blocking',1,'']]],
  ['a_20real_20time_20control_20system_14',['What is a real-time control system?',['../index.html#autotoc_md180',1,'']]],
  ['a_20slave_15',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['a_20socket_20must_20now_20say_20so_16',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['a_20string_20may_20contain_20nul_20and_20string_20length_20is_20the_20authority_17',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['aarch64_18',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['access_20point_20softap_19',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['accessors_20',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['accumulator_20floor_20map_20scm_21',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['acknowledgements_22',['Acknowledgements',['../index.html#autotoc_md209',1,'']]],
  ['actually_20drives_20a_20pin_23',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['adaptive_20real_20time_20garbage_20collection_24',['Adaptive real-time garbage collection',['../index.html#autotoc_md23',1,'']]],
  ['addressable_20led_20strip_20neopixel_25',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md99',1,'']]],
  ['addressable_20leds_20ws2812_20scm_26',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md104',1,'']]],
  ['advanced_27',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_28',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['ai_20and_20machine_20to_20machine_29',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['ai_20orchestration_20and_20the_20robot_20stack_30',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['air_20updates_31',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['air_20updates_20without_20reboot_32',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['algebra_33',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['all_20platforms_34',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md188',1,'']]],
  ['already_20inside_35',['The documentation is already inside',['../index.html#autotoc_md9',1,'']]],
  ['already_20rooted_20for_20you_36',['What is already rooted for you',['../index.html#autotoc_md64',1,'']]],
  ['an_20embedded_20board_37',['Flash an embedded board',['../index.html#package-flash',1,'']]],
  ['an_20rtos_38',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md206',1,'']]],
  ['and_20aarch64_39',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['and_20arq_20llip_20serial_20scm_40',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['and_20ascii_20render_41',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['and_20boards_42',['Supported Platforms and Boards',['../index.html#supported-platforms',1,'']]],
  ['and_20c_20api_43',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['and_20char_20ready_44',['&lt;span class=&quot;tt&quot;&gt;u8-ready?&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;char-ready?&lt;/span&gt;',['../index.html#autotoc_md163',1,'']]],
  ['and_20collisions_45',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['and_20conformance_46',['Language and Conformance',['../index.html#autotoc_md190',1,'']]],
  ['and_20conformance_47',['1. Overview and conformance',['../index.html#bacnet-overview',1,'']]],
  ['and_20development_20tools_48',['Diagnostics and Development Tools',['../index.html#autotoc_md76',1,'']]],
  ['and_20discovery_49',['2. Sessions and discovery',['../index.html#bacnet-discovery',1,'']]],
  ['and_20evaluation_50',['Environments and Evaluation',['../index.html#autotoc_md155',1,'']]],
  ['and_20flash_51',['Build and Flash',['../index.html#autotoc_md15',1,'']]],
  ['and_20gc_20tuning_52',['and GC Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['and_20global_20control_53',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['and_20hashing_20details_54',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['and_20limits_55',['5. Requirements and limits',['../index.html#bacnet-limits',1,'']]],
  ['and_20list_20structures_56',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['and_20lists_57',['Pairs and Lists',['../index.html#autotoc_md142',1,'']]],
  ['and_20machine_20to_20machine_58',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['and_20macro_59',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['and_20memory_20tuning_60',['GC and memory tuning',['../index.html#autotoc_md84',1,'']]],
  ['and_20motors_20pca9685_20scm_61',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md103',1,'']]],
  ['and_20naming_62',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['and_20non_20symbol_20keys_63',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['and_20on_20board_20display_20esp32_20s3_20eye_64',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['and_20operation_65',['Integration and Operation',['../index.html#autotoc_md201',1,'']]],
  ['and_20output_66',['Input and Output',['../index.html#autotoc_md159',1,'']]],
  ['and_20pre_20reserve_67',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['and_20profinet_20interface_68',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['and_20scheme_69',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['and_20scm_20are_20not_20the_20same_20thing_70',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['and_20start_20the_20car_71',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['and_20string_20length_20is_20the_20authority_72',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['and_20system_73',['Timing and system',['../index.html#autotoc_md83',1,'']]],
  ['and_20tail_20calls_74',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['and_20the_20meaning_20of_200_75',['The bulk form, and the meaning of &lt;span class=&quot;tt&quot;&gt;0&lt;/span&gt;',['../index.html#autotoc_md161',1,'']]],
  ['and_20the_20robot_20stack_76',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['and_20what_20actually_20drives_20a_20pin_77',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['and_20what_20is_20not_78',['and what is not',['../index.html#autotoc_md8',1,'What is in the image, and what is not'],['../index.html#autotoc_md6',1,'What is the same as Linux, and what is not']]],
  ['and_20why_20it_20exists_79',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['and_20writing_20properties_80',['3. Reading and writing properties',['../index.html#bacnet-properties',1,'']]],
  ['answering_20as_20a_20device_20object_81',['4. Answering as a Device object',['../index.html#bacnet-device',1,'']]],
  ['any_20directory_82',['Running from any directory',['../index.html#autotoc_md5',1,'']]],
  ['api_83',['API',['../index.html#profinet-api',1,'5.2 The API'],['../index.html#autotoc_md53',1,'Language Internals and C++ API']]],
  ['api_20for_20new_20lisp_20primitives_84',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#open-api',1,'']]],
  ['api_20llip_20client_20scm_85',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md90',1,'']]],
  ['applications_20as_20virtual_20machines_86',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['arbitrary_20precision_20integers_20bignums_87',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['architecture_88',['Role in the Supervisory Architecture',['../index.html#autotoc_md93',1,'']]],
  ['architecture_20internals_89',['LambLisp Architecture Internals',['../index.html#autotoc_md32',1,'']]],
  ['architecture_20notes_90',['7. Architecture Notes',['../index.html#fwd-arch-notes',1,'']]],
  ['arduino_20embedded_20i_20o_91',['Arduino / Embedded I/O',['../index.html#llarduino',1,'']]],
  ['arduino_20libraries_92',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['are_20first_20class_20data_20types_93',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['are_20not_20the_20same_20thing_94',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['are_20porting_20from_20chez_95',['If you are porting from Chez',['../index.html#autotoc_md162',1,'']]],
  ['are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_96',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['are_20wrappers_20around_20hierarchical_20dictionaries_97',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['around_20hierarchical_20dictionaries_98',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['arq_20llip_20serial_20scm_99',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['array_100',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['array_20math_20linear_20algebra_101',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['arrays_20array_102',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['as_20a_20device_20object_103',['4. Answering as a Device object',['../index.html#bacnet-device',1,'']]],
  ['as_20a_20master_104',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['as_20a_20slave_105',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['as_20linux_20and_20what_20is_20not_106',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['as_20modbus_20controller_107',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['as_20modbus_20peripheral_108',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['as_20the_20universal_20glue_109',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['as_20virtual_20machines_110',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['ascii_20render_111',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['asked_20questions_112',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['ast_20→_20bytecode_20→_20native_20code_113',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['asynchronous_20work_20—_20deferred_20task_20queue_114',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['at_20startup_115',['What Happens at Startup',['../index.html#startup',1,'']]],
  ['authority_116',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['autonomous_20fill_20behaviour_117',['3.3 Autonomous Fill Behaviour',['../index.html#fwd-autonomous',1,'']]],
  ['autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_118',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]]
];
