var searchData=
[
  ['embedded_20board_0',['Flash an embedded board',['../index.html#package-flash',1,'']]],
  ['embedded_20hardware_1',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['embedded_20i_20o_2',['Arduino / Embedded I/O',['../index.html#llarduino',1,'']]],
  ['embedded_20python_20derivatives_3',['Why not use embedded Python derivatives?',['../index.html#autotoc_md197',1,'']]],
  ['enforce_4',['Two rules the macro cannot enforce',['../index.html#autotoc_md66',1,'']]],
  ['environment_5',['Unified Distributed Environment',['../index.html#autotoc_md96',1,'']]],
  ['environment_20is_20a_20hierarchical_20dictionary_6',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['environment_20operations_7',['Dictionary (Environment) Operations',['../index.html#autotoc_md75',1,'']]],
  ['environments_20and_20evaluation_8',['Environments and Evaluation',['../index.html#autotoc_md155',1,'']]],
  ['error_20handling_9',['2.5 Error Handling',['../index.html#modbus-errors',1,'']]],
  ['error_20tags_10',['Error tags',['../index.html#autotoc_md121',1,'']]],
  ['escape_20only_20call_20with_20current_20continuation_11',['Why only escape-only &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md193',1,'']]],
  ['esp32_12',['Deploy to ESP32',['../index.html#deploy-esp32',1,'']]],
  ['esp32_20hardware_13',['ESP32 Hardware',['../index.html#autotoc_md13',1,'']]],
  ['esp32_20s3_14',['4.2 ESP32-S3',['../index.html#modbus-esp32',1,'']]],
  ['esp32_20s3_20eye_15',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['esp32_20system_16',['ESP32 System',['../index.html#autotoc_md114',1,'']]],
  ['eval_20operation_17',['The eval Operation',['../index.html#autotoc_md89',1,'']]],
  ['eval_20sandbox_20demo_20sandbox_20scm_18',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md123',1,'']]],
  ['evaluation_19',['Environments and Evaluation',['../index.html#autotoc_md155',1,'']]],
  ['events_20not_20exceptions_20',['2.4 Events, Not Exceptions',['../index.html#profibus-events',1,'']]],
  ['example_21',['Example',['../index.html#fwd-run',1,'6. Running the Example'],['../index.html#fwd-extend',1,'7.3 Extending the Example'],['../index.html#autotoc_md81',1,'Example'],['../index.html#autotoc_md85',1,'Example']]],
  ['example_3a_20autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_22',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['example_3a_20supervisory_20control_20of_20the_20freenove_204wd_20car_23',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md94',1,'']]],
  ['examples_24',['Worked Examples',['../index.html#worked-examples',1,'']]],
  ['exception_20handling_25',['Exception Handling',['../index.html#autotoc_md168',1,'']]],
  ['exceptions_26',['2.4 Events, Not Exceptions',['../index.html#profibus-events',1,'']]],
  ['execution_20environment_20is_20a_20hierarchical_20dictionary_27',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['execution_20tiers_3a_20ast_20→_20bytecode_20→_20native_20code_28',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['existing_20c_20arduino_20libraries_29',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['exists_30',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['expander_20pcf8574_20scm_31',['I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)',['../index.html#autotoc_md108',1,'']]],
  ['extending_20the_20example_32',['7.3 Extending the Example',['../index.html#fwd-extend',1,'']]],
  ['extension_33',['C++ Extension',['../index.html#autotoc_md50',1,'']]],
  ['extensions_34',['Extensions',['../index.html#autotoc_md74',1,'LambLisp Extensions'],['../index.html#language-extensions',1,'Language Extensions']]],
  ['eye_35',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['eye_20cam_20scm_20live_20preview_20layer_36',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]]
];
