var searchData=
[
  ['waypoint_20navigation_0',['3.4 Waypoint Navigation',['../index.html#fwd-nav',1,'']]],
  ['waypoints_20to_20the_20car_1',['4.3 Feeding Waypoints to the Car',['../index.html#fwd-jetson-waypoints',1,'']]],
  ['what_20actually_20drives_20a_20pin_2',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['what_20are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_3',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['what_20happens_20at_20startup_4',['What Happens at Startup',['../index.html#startup',1,'']]],
  ['what_20hardware_20does_20lamblisp_20run_20on_5',['What hardware does LambLisp run on?',['../index.html#autotoc_md173',1,'']]],
  ['what_20is_20a_20real_20time_20control_20system_6',['What is a real-time control system?',['../index.html#autotoc_md180',1,'']]],
  ['what_20is_20already_20rooted_20for_20you_7',['What is already rooted for you',['../index.html#autotoc_md64',1,'']]],
  ['what_20is_20bytecode_20ncg_20compilation_8',['What is bytecode / NCG compilation?',['../index.html#autotoc_md186',1,'']]],
  ['what_20is_20in_20the_20image_20and_20what_20is_20not_9',['What is in the image, and what is not',['../index.html#autotoc_md8',1,'']]],
  ['what_20is_20in_20the_20package_10',['What is in the package',['../index.html#package-contents',1,'']]],
  ['what_20is_20llip_11',['What is LLIP?',['../index.html#autotoc_md182',1,'']]],
  ['what_20is_20not_12',['what is not',['../index.html#autotoc_md8',1,'What is in the image, and what is not'],['../index.html#autotoc_md6',1,'What is the same as Linux, and what is not']]],
  ['what_20is_20the_20memory_20footprint_13',['What is the memory footprint?',['../index.html#autotoc_md208',1,'']]],
  ['what_20is_20the_20same_20as_20linux_20and_20what_20is_20not_14',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['what_20it_20looks_20like_20when_20you_20get_20it_20wrong_15',['What it looks like when you get it wrong',['../index.html#autotoc_md68',1,'']]],
  ['what_20needs_20protecting_16',['What needs protecting',['../index.html#autotoc_md65',1,'']]],
  ['what_20s_20in_20the_20package_17',['What&apos;s in the package?',['../index.html#whats-in-the-package',1,'']]],
  ['what_20you_20get_18',['1. What You Get',['../index.html#fieldbus-what-you-get',1,'']]],
  ['what_20you_20need_19',['What you need',['../index.html#autotoc_md2',1,'']]],
  ['when_20it_20does_20not_20work_20',['When it does not work',['../index.html#package-troubleshooting',1,'']]],
  ['when_20you_20get_20it_20wrong_21',['What it looks like when you get it wrong',['../index.html#autotoc_md68',1,'']]],
  ['where_20does_20lamblisp_20sit_20in_20the_20lisp_20landscape_22',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md195',1,'']]],
  ['where_20these_20run_20and_20what_20actually_20drives_20a_20pin_23',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['which_20ports_20have_20three_20states_24',['Which ports have three states',['../index.html#autotoc_md164',1,'']]],
  ['which_20release_20is_20in_20the_20image_25',['Which release is in the image',['../index.html#autotoc_md10',1,'']]],
  ['why_20is_20it_20called_20lamblisp_20instead_20of_20scheme_26',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md191',1,'']]],
  ['why_20it_20exists_27',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['why_20lamblisp_28',['Why &lt;em&gt;LambLisp&lt;/em&gt;?',['../index.html#why-lamblisp',1,'']]],
  ['why_20lisp_29',['Why Lisp?',['../index.html#autotoc_md18',1,'']]],
  ['why_20not_20use_20embedded_20python_20derivatives_30',['Why not use embedded Python derivatives?',['../index.html#autotoc_md197',1,'']]],
  ['why_20not_20use_20llvm_20for_20native_20code_20generation_31',['Why not use LLVM for native code generation?',['../index.html#autotoc_md199',1,'']]],
  ['why_20only_20escape_20only_20call_20with_20current_20continuation_32',['Why only escape-only &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md193',1,'']]],
  ['why_20the_20compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_33',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['why_20three_20tiers_34',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['widely_20recognized_20scheme_20language_20specification_35',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md21',1,'']]],
  ['wifi_36',['WiFi',['../index.html#autotoc_md78',1,'']]],
  ['wifi_20access_20point_20softap_37',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['wifi_20station_20—_20advanced_38',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['windows_39',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['wire_40',['I2C (Wire)',['../index.html#autotoc_md77',1,'']]],
  ['wire_20bus_41',['OneWire (1-Wire Bus)',['../index.html#onewire',1,'']]],
  ['wire_20contract_20nvs_42',['The loader wire contract (NVS)',['../index.html#autotoc_md79',1,'']]],
  ['wire_20format_43',['Wire Format',['../index.html#autotoc_md86',1,'']]],
  ['wiring_44',['4. RS-485 Wiring',['../index.html#profibus-wiring',1,'']]],
  ['with_20c_20c_20code_45',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md204',1,'']]],
  ['with_20c_20c_20on_20micro_20controllers_46',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['with_20c_20code_47',['Runtime collaboration with C++ code',['../index.html#autotoc_md30',1,'']]],
  ['with_20current_20continuation_48',['Why only escape-only &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md193',1,'']]],
  ['with_20real_20time_20lamblisp_49',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['with_20the_20freenove_204wd_20car_50',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['without_20an_20rtos_51',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md206',1,'']]],
  ['without_20reboot_52',['Hot-Reload Without Reboot',['../index.html#llip-hotreload',1,'']]],
  ['without_20reboot_53',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['without_20reflashing_54',['How do I update code without reflashing?',['../index.html#autotoc_md177',1,'']]],
  ['work_55',['When it does not work',['../index.html#package-troubleshooting',1,'']]],
  ['work_20—_20deferred_20task_20queue_56',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['worked_20example_3a_20autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_57',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['worked_20example_3a_20supervisory_20control_20of_20the_20freenove_204wd_20car_58',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md94',1,'']]],
  ['worked_20examples_59',['Worked Examples',['../index.html#worked-examples',1,'']]],
  ['works_20on_20a_20port_60',['How blocking works on a port',['../index.html#port-blocking',1,'']]],
  ['world_20pauses_61',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['wrappers_20around_20hierarchical_20dictionaries_62',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['wrappers_20sonar_20scm_63',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md111',1,'']]],
  ['write_20callbacks_64',['3.5 Write Callbacks',['../index.html#modbus-write-callbacks',1,'']]],
  ['writing_20properties_65',['3. Reading and writing properties',['../index.html#bacnet-properties',1,'']]],
  ['wrong_66',['What it looks like when you get it wrong',['../index.html#autotoc_md68',1,'']]],
  ['ws2812_20addressable_20led_20strip_20neopixel_67',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md99',1,'']]],
  ['ws2812_20scm_68',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md104',1,'']]]
];
