var searchData=
[
  ['c_0',['Camera / LCD primitives (C++)',['../index.html#autotoc_md101',1,'']]],
  ['c_20—_20footprint_1',['Group C — Footprint',['../index.html#autotoc_md51',1,'']]],
  ['c_20api_2',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['c_20arduino_20libraries_3',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['c_20c_20code_4',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md204',1,'']]],
  ['c_20c_20on_20micro_20controllers_5',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['c_20code_6',['C code',['../index.html#autotoc_md204',1,'Does LambLisp interoperate with C/C++ code?'],['../index.html#autotoc_md30',1,'Runtime collaboration with C++ code']]],
  ['c_20extension_7',['C++ Extension',['../index.html#autotoc_md50',1,'']]],
  ['c_20integration_8',['C++ Integration',['../index.html#arch-cpp',1,'']]],
  ['c_20on_20micro_20controllers_9',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['c_20procedures_10',['Garbage Collection Rules for C++ Procedures',['../index.html#mop3-gc-rules',1,'']]],
  ['call_20with_20current_20continuation_11',['Why only escape-only &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md193',1,'']]],
  ['callbacks_12',['3.5 Write Callbacks',['../index.html#modbus-write-callbacks',1,'']]],
  ['called_20lamblisp_20instead_20of_20scheme_13',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md191',1,'']]],
  ['calls_14',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['cam_20scm_20live_20preview_20layer_15',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]],
  ['camera_20and_20on_20board_20display_20esp32_20s3_20eye_16',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['camera_20lcd_20primitives_20c_17',['Camera / LCD primitives (C++)',['../index.html#autotoc_md101',1,'']]],
  ['can_20i_20use_20lamblisp_20without_20an_20rtos_18',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md206',1,'']]],
  ['can_20throw_19',['Procedures that can throw',['../index.html#autotoc_md67',1,'']]],
  ['cannot_20enforce_20',['Two rules the macro cannot enforce',['../index.html#autotoc_md66',1,'']]],
  ['car_21',['Car',['../index.html#fwd-jetson-waypoints',1,'4.3 Feeding Waypoints to the Car'],['../index.html#fwd-run-car',1,'6.2 Flash and Start the Car'],['../index.html#fwd-floor-mapping',1,'Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car'],['../index.html#autotoc_md94',1,'Worked Example: Supervisory Control of the Freenove 4WD Car']]],
  ['car_20code_22',['3. On-Board Car Code',['../index.html#fwd-onboard',1,'']]],
  ['car_20kit_20—_20peripheral_20summary_23',['Freenove 4WD Car Kit — Peripheral Summary',['../index.html#autotoc_md100',1,'']]],
  ['ceiling_20and_20why_20it_20exists_24',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['cell_20memory_20model_20and_20list_20structures_25',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['certification_20and_20naming_26',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['char_20ready_27',['&lt;span class=&quot;tt&quot;&gt;u8-ready?&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;char-ready?&lt;/span&gt;',['../index.html#autotoc_md163',1,'']]],
  ['characters_28',['Characters',['../index.html#autotoc_md144',1,'']]],
  ['chez_29',['If you are porting from Chez',['../index.html#autotoc_md162',1,'']]],
  ['class_20data_20types_30',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['class_20hierarchical_20dictionaries_31',['First-class hierarchical dictionaries',['../index.html#autotoc_md25',1,'']]],
  ['client_20api_20llip_20client_20scm_32',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md90',1,'']]],
  ['client_20scm_33',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md90',1,'']]],
  ['client_3a_20tools_20llip_34',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['cloud_20server_35',['6.1 Start the Cloud Server',['../index.html#fwd-run-cloud',1,'']]],
  ['cloud_20strategy_20server_36',['5. Cloud Strategy Server',['../index.html#fwd-cloud',1,'']]],
  ['code_37',['Code',['../index.html#fwd-onboard',1,'3. On-Board Car Code'],['../index.html#arch-pipeline',1,'Execution Tiers: AST → Bytecode → Native Code']]],
  ['code_38',['code',['../index.html#autotoc_md204',1,'Does LambLisp interoperate with C/C++ code?'],['../index.html#autotoc_md30',1,'Runtime collaboration with C++ code']]],
  ['code_20generation_39',['Why not use LLVM for native code generation?',['../index.html#autotoc_md199',1,'']]],
  ['code_20generator_20ncg_40',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['code_20lifecycle_3a_20incremental_20hot_20reload_41',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['code_20run_20on_20all_20platforms_42',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md188',1,'']]],
  ['code_20without_20reflashing_43',['How do I update code without reflashing?',['../index.html#autotoc_md177',1,'']]],
  ['codes_44',['2.3 Function Codes',['../index.html#modbus-function-codes',1,'']]],
  ['codes_20symbols_20for_20modbus_20request_45',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]],
  ['collaboration_20with_20c_20code_46',['Runtime collaboration with C++ code',['../index.html#autotoc_md30',1,'']]],
  ['collecting_20the_20map_47',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['collection_48',['Garbage Collection',['../index.html#arch-gc',1,'']]],
  ['collection_49',['Adaptive real-time garbage collection',['../index.html#autotoc_md23',1,'']]],
  ['collection_20rules_20for_20c_20procedures_50',['Garbage Collection Rules for C++ Procedures',['../index.html#mop3-gc-rules',1,'']]],
  ['collisions_51',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['combination_20with_20c_20c_20on_20micro_20controllers_52',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['command_20line_20client_3a_20tools_20llip_53',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['compatibility_54',['Detailed Compatibility',['../index.html#autotoc_md131',1,'']]],
  ['compatibility_55',['A note on host compatibility',['../index.html#autotoc_md11',1,'']]],
  ['compatibility_20matrix_56',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['compilation_57',['compilation',['../index.html#autotoc_md26',1,'Incremental, just-in-time compilation'],['../index.html#autotoc_md186',1,'What is bytecode / NCG compilation?']]],
  ['compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_58',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['compiler_20organization_59',['Interpreter &amp;amp; compiler organization',['../index.html#arch-interp',1,'']]],
  ['concepts_60',['Concepts',['../index.html#autotoc_md179',1,'']]],
  ['confirm_20rollback_20model_61',['The boot-confirm / rollback model',['../index.html#autotoc_md80',1,'']]],
  ['conformance_62',['Language and Conformance',['../index.html#autotoc_md190',1,'']]],
  ['conformance_63',['1. Overview and conformance',['../index.html#bacnet-overview',1,'']]],
  ['connect_20to_20the_20repl_64',['Connect to the REPL',['../index.html#autotoc_md16',1,'']]],
  ['connecting_65',['2.1 Connecting',['../index.html#modbus-controller-connect',1,'']]],
  ['connection_20lifecycle_66',['Connection Lifecycle',['../index.html#autotoc_md87',1,'']]],
  ['connections_67',['4.1 Connections',['../index.html#fwd-jetson-connect',1,'']]],
  ['constructors_68',['Task Constructors',['../index.html#autotoc_md112',1,'']]],
  ['contain_20nul_20and_20string_20length_20is_20the_20authority_69',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['container_70',['Running LambLisp in a Container',['../index.html#containers',1,'']]],
  ['container_71',['Flashing from a container',['../index.html#flashing-from-a-container',1,'']]],
  ['containers_72',['Containers',['../index.html#autotoc_md63',1,'']]],
  ['continuation_73',['Why only escape-only &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md193',1,'']]],
  ['contract_20nvs_74',['The loader wire contract (NVS)',['../index.html#autotoc_md79',1,'']]],
  ['control_75',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['control_76',['Real-time control',['../index.html#autotoc_md19',1,'']]],
  ['control_20applications_20as_20virtual_20machines_77',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['control_20cycle_78',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md43',1,'']]],
  ['control_20demo_20supervisor_20scm_79',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md122',1,'']]],
  ['control_20features_80',['Control Features',['../index.html#autotoc_md153',1,'']]],
  ['control_20of_20the_20freenove_204wd_20car_81',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md94',1,'']]],
  ['control_20system_82',['What is a real-time control system?',['../index.html#autotoc_md180',1,'']]],
  ['controller_83',['Controller',['../index.html#modbus-controller',1,'2. LambLisp as Modbus Controller'],['../index.html#autotoc_md98',1,'PCA9685 PWM Controller']]],
  ['controller_20function_20codes_20symbols_20for_20modbus_20request_84',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]],
  ['controller_20functions_85',['Controller Functions',['../index.html#autotoc_md115',1,'']]],
  ['controllers_86',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md202',1,'']]],
  ['convenience_20wrappers_20sonar_20scm_87',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md111',1,'']]],
  ['cooperative_20scheduling_88',['Behaviors: Cooperative Scheduling',['../index.html#behaviors',1,'']]],
  ['core_20language_89',['Core Language',['../index.html#autotoc_md132',1,'']]],
  ['coverage_20plan_90',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['coverage_20planner_91',['5.1 Boustrophedon Coverage Planner',['../index.html#fwd-cloud-planner',1,'']]],
  ['coverage_20summary_92',['Coverage Summary',['../index.html#autotoc_md129',1,'']]],
  ['cryptography_93',['Cryptography',['../index.html#crypto',1,'']]],
  ['csv_94',['CSV',['../index.html#csv',1,'']]],
  ['cuda_20integration_95',['CUDA Integration',['../index.html#cuda-integration',1,'']]],
  ['current_20continuation_96',['Why only escape-only &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md193',1,'']]],
  ['cycle_97',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md43',1,'']]]
];
