var searchData=
[
  ['s_20in_20the_20package_0',['What&apos;s in the package?',['../index.html#whats-in-the-package',1,'']]],
  ['s3_1',['4.2 ESP32-S3',['../index.html#modbus-esp32',1,'']]],
  ['s3_20eye_2',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['same_20as_20linux_20and_20what_20is_20not_3',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['same_20scheme_20code_20run_20on_20all_20platforms_4',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md188',1,'']]],
  ['same_20thing_5',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['sandbox_20demo_20sandbox_20scm_6',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md123',1,'']]],
  ['sandbox_20scm_7',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md123',1,'']]],
  ['say_20so_8',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['scalability_9',['Scalability',['../index.html#arch-scalability',1,'']]],
  ['scheduling_10',['Behaviors: Cooperative Scheduling',['../index.html#behaviors',1,'']]],
  ['scheme_11',['Scheme',['../index.html#arch-history',1,'Brief history of Lisp and Scheme'],['../index.html#autotoc_md191',1,'Why is it called LambLisp instead of Scheme?']]],
  ['scheme_20code_20run_20on_20all_20platforms_12',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md188',1,'']]],
  ['scheme_20implementations_13',['Other Scheme Implementations',['../index.html#competitors',1,'']]],
  ['scheme_20language_20specification_14',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md21',1,'']]],
  ['scheme_20libraries_15',['Bundled Scheme Libraries',['../index.html#scheme-libraries',1,'']]],
  ['scm_16',['scm',['../index.html#fwd-floor-map-scm',1,'3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)'],['../index.html#autotoc_md104',1,'Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)'],['../index.html#autotoc_md106',1,'Buzzer (&lt;span class=&quot;tt&quot;&gt;Buzzer.scm&lt;/span&gt;)'],['../index.html#autotoc_md90',1,'Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)'],['../index.html#llip-device-serve',1,'Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)'],['../index.html#autotoc_md123',1,'Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)'],['../index.html#llip-http',1,'HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)'],['../index.html#autotoc_md110',1,'I2C Bus Utilities (&lt;span class=&quot;tt&quot;&gt;I2C.scm&lt;/span&gt;)'],['../index.html#autotoc_md108',1,'I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)'],['../index.html#autotoc_md105',1,'LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)'],['../index.html#autotoc_md109',1,'Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)'],['../index.html#autotoc_md125',1,'Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)'],['../index.html#autotoc_md126',1,'Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)'],['../index.html#llip-serial',1,'Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)'],['../index.html#autotoc_md91',1,'Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)'],['../index.html#autotoc_md103',1,'Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)'],['../index.html#autotoc_md111',1,'Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)'],['../index.html#autotoc_md122',1,'Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)'],['../index.html#autotoc_md124',1,'Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)'],['../index.html#autotoc_md107',1,'Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)']]],
  ['scm_20are_20not_20the_20same_20thing_17',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['scm_20live_20preview_20layer_18',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]],
  ['scoping_19',['Lexical scoping',['../index.html#autotoc_md27',1,'']]],
  ['security_20',['Security',['../index.html#autotoc_md92',1,'']]],
  ['sensor_20lightsensor_20scm_21',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md109',1,'']]],
  ['serial_22',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['serial_20scm_23',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['serial_20transport_20and_20arq_20llip_20serial_20scm_24',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['serve_20loop_25',['3.4 The Serve Loop',['../index.html#modbus-serve-loop',1,'']]],
  ['server_26',['Server',['../index.html#fwd-cloud',1,'5. Cloud Strategy Server'],['../index.html#fwd-cloud-bee',1,'5.3 Bee Strategy Server'],['../index.html#fwd-run-cloud',1,'6.1 Start the Cloud Server']]],
  ['server_20llip_20server_20scm_27',['Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)',['../index.html#autotoc_md91',1,'']]],
  ['server_20scm_28',['Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)',['../index.html#autotoc_md91',1,'']]],
  ['service_20leds_20scm_29',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['service_20loop_30',['2.3 The Service Loop',['../index.html#profibus-loop',1,'']]],
  ['serving_20llip_20transport_20scm_31',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['servos_20and_20motors_20pca9685_20scm_32',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md103',1,'']]],
  ['sessions_20and_20discovery_33',['2. Sessions and discovery',['../index.html#bacnet-discovery',1,'']]],
  ['setup_34',['2. Hardware Setup',['../index.html#fwd-hw',1,'']]],
  ['sit_20in_20the_20lisp_20landscape_35',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md195',1,'']]],
  ['size_20dma_20memory_20and_20pre_20reserve_36',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['sizing_20and_20collisions_37',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['slave_38',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['slave_39',['PROFIBUS DP slave',['../index.html#autotoc_md119',1,'']]],
  ['slaves_40',['2.2 Declaring Slaves',['../index.html#profibus-add-slave',1,'']]],
  ['sntp_41',['Network Time (SNTP)',['../index.html#nettime',1,'']]],
  ['so_42',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['socket_20must_20now_20say_20so_43',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md211',1,'']]],
  ['softap_44',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['sonar_20convenience_20wrappers_20sonar_20scm_45',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md111',1,'']]],
  ['sonar_20hc_20sr04_46',['Ultrasonic Sonar (HC-SR04)',['../index.html#ultrasonic-sonar-hc-sr04',1,'']]],
  ['sonar_20scm_47',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md111',1,'']]],
  ['source_48',['Is LambLisp open source?',['../index.html#autotoc_md175',1,'']]],
  ['specification_49',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md21',1,'']]],
  ['speed_50',['Group B — Speed',['../index.html#autotoc_md49',1,'']]],
  ['spi_20bus_51',['SPI Bus',['../index.html#spi',1,'']]],
  ['sr04_52',['Ultrasonic Sonar (HC-SR04)',['../index.html#ultrasonic-sonar-hc-sr04',1,'']]],
  ['stack_53',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['stack_20size_20dma_20memory_20and_20pre_20reserve_54',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['start_20the_20car_55',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['start_20the_20cloud_20server_56',['6.1 Start the Cloud Server',['../index.html#fwd-run-cloud',1,'']]],
  ['start_3a_20the_20package_20you_20received_57',['Quick Start: The Package You Received',['../index.html#quick-start-package',1,'']]],
  ['start_3a_20try_20lamblisp_20in_20your_20browser_58',['Quick Start: Try LambLisp in Your Browser',['../index.html#quick-start-browser',1,'']]],
  ['start_3a_20try_20lamblisp_20on_20linux_59',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['start_3a_20try_20lamblisp_20on_20windows_60',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['started_61',['Getting Started',['../index.html#autotoc_md170',1,'']]],
  ['started_20with_20real_20time_20lamblisp_62',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['startup_63',['What Happens at Startup',['../index.html#startup',1,'']]],
  ['stateful_20objects_64',['Stateful Objects',['../index.html#autotoc_md69',1,'']]],
  ['stateless_20procedures_65',['Stateless Procedures',['../index.html#arch-mop3',1,'']]],
  ['states_66',['Which ports have three states',['../index.html#autotoc_md164',1,'']]],
  ['station_20—_20advanced_67',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['stop_20the_20world_20pauses_68',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['store_20and_20ascii_20render_69',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['strategy_20module_70',['3.5 Bee Strategy Module',['../index.html#fwd-bee-onboard',1,'']]],
  ['strategy_20server_71',['Strategy Server',['../index.html#fwd-cloud',1,'5. Cloud Strategy Server'],['../index.html#fwd-cloud-bee',1,'5.3 Bee Strategy Server']]],
  ['string_20length_20is_20the_20authority_72',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['string_20may_20contain_20nul_20and_20string_20length_20is_20the_20authority_73',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['strings_74',['Strings',['../index.html#autotoc_md146',1,'']]],
  ['strip_20neopixel_75',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md99',1,'']]],
  ['struct_76',['Binary framing (struct)',['../index.html#struct',1,'']]],
  ['structured_20data_77',['Structured Data',['../index.html#structured-data',1,'']]],
  ['structures_78',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['sub_20microsecond_20isr_79',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md44',1,'']]],
  ['summary_80',['Summary',['../index.html#modbus-build-flags',1,'4.3 Build Flag Summary'],['../index.html#autotoc_md129',1,'Coverage Summary'],['../index.html#autotoc_md100',1,'Freenove 4WD Car Kit — Peripheral Summary']]],
  ['summary_81',['Key feature summary',['../index.html#autotoc_md31',1,'']]],
  ['supervisor_82',['4. Jetson Supervisor',['../index.html#fwd-jetson',1,'']]],
  ['supervisor_20on_20the_20jetson_83',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['supervisor_20scm_84',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md122',1,'']]],
  ['supervisory_20architecture_85',['Role in the Supervisory Architecture',['../index.html#autotoc_md93',1,'']]],
  ['supervisory_20control_20demo_20supervisor_20scm_86',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md122',1,'']]],
  ['supervisory_20control_20of_20the_20freenove_204wd_20car_87',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md94',1,'']]],
  ['support_88',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['supported_20platforms_20and_20boards_89',['Supported Platforms and Boards',['../index.html#supported-platforms',1,'']]],
  ['symbol_20keys_90',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['symbols_91',['Symbols',['../index.html#autotoc_md140',1,'']]],
  ['symbols_20for_20modbus_20request_92',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]],
  ['sync_93',['4.4 Digital Twin Sync',['../index.html#fwd-jetson-twin',1,'']]],
  ['syntax_20forms_94',['Syntax Forms',['../index.html#autotoc_md71',1,'']]],
  ['system_95',['System',['../index.html#autotoc_md114',1,'ESP32 System'],['../index.html#autotoc_md134',1,'Type System']]],
  ['system_96',['system',['../index.html#autotoc_md62',1,'Lightweight object system'],['../index.html#autotoc_md83',1,'Timing and system'],['../index.html#autotoc_md180',1,'What is a real-time control system?']]],
  ['system_20interface_97',['System Interface',['../index.html#autotoc_md166',1,'']]]
];
