;;; Copyright 2026 by Frobenius Norm LLC 2026-05-16
;;; Free for non-commercial use. Commercial use requires a license.
(syslog "Loading Cuda\n")

(define have-Cuda (dict-ref? (current-environment) 'cudaGetDeviceCount))

(unless have-Cuda (info "CUDA not available\n"))

(define (cuda-printprops-brief all-props)
  (let* ((brief-prop-keys '(name totalGlobalMem
				 sharedMemPerBlock regsPerBlock
				 warpSize maxThreadsPerBlock maxThreadsDim maxGridSize totalConstMem
				 multiProcessorCount regsPerMultiprocessor maxThreadsPerMultiProcessor sharedMemPerMultiprocessor
				 )
			  )
	 (brief-props (reverse! (alist-subset brief-prop-keys all-props)))
	 )
    (cuda-printprops brief-props)
    )
  )

(define (cuda-printprop p)
  (let ((key (car p))
	(val (cdr p))
	)

    (if (eq? key 'uuid)	(info "(~a . #u8(xxxx)\n" key)
	(if (bytevector? val)
	    (if (eq? (quotient (bytevector-length val) 4) 2)
		(info "(~a . (~a ~a))\n" key (bytevector-s32-native-ref val 0) (bytevector-s32-native-ref val 4))
		(info "(~a . (~a ~a ~a))\n" key (bytevector-s32-native-ref val 0) (bytevector-s32-native-ref val 4) (bytevector-s32-native-ref val 8))
		)
	    (info "(~a . ~a)\n" key val)
	    )
	)
    )
  )

(define (cuda-printprops props)
  (info "(\n")
  (letrec ((print-rest (lambda (props)
			 (unless (null? props)
			   (cuda-printprop (car props))
			   (print-rest (cdr props))
			   )
			 )
		       )
	   )
    (print-rest props)
    )
  (info ")\n")
  )

(define (cudaStart)
  (letrec ((me "cudaStart")
	   (ndev (cudaGetDeviceCount))
	   (printit (lambda (n)
		      (if (>= n 0) (begin
				     (info "~a cuda Device ~a\n" me n)
				     (cuda-printprops-brief (cudaGetDeviceProperties n))
				     (printit (- n 1))
				     )
			  )
		      )
		    )
	   )
    (news "~a Cuda device(s) found\n" ndev)
    (printit (- ndev 1))
    )
  )

(define (cudaTest1)
  (news "cudaTest in progress\n")
  (letrec* ((N (* 10 1024 1024))
	    (h_A (make-float32-vector N))
	    (h_B (make-float32-vector N))
	    (h_C (make-float32-vector N))

	    (Nbytes (* N (sizeof 1.0)))
	    (d_A (cudaMalloc Nbytes))
	    (d_B (cudaMalloc Nbytes))
	    (d_C (cudaMalloc Nbytes))
	    )
    (news "(N ~a)\n" N)
    (news "Randomizing h_A\n")
    (array-randomize01! h_A)
    (news "Randomizing h_B\n")
    (array-randomize01! h_B)
    (news "Filling h_C\n")
    (array-fill! h_C 0.0)
    (news "Host arrays initialized\n")
    (cudaMemcpy d_A (array-data h_A) Nbytes 'cudaMemcpyHostToDevice)
    (cudaMemcpy d_B (array-data h_B) Nbytes 'cudaMemcpyHostToDevice)
    (cudakernel-vectorAdd d_A d_B d_C N)
    (cudaDeviceSynchronize)
    (cudaMemcpy (array-data h_C) d_C Nbytes 'cudaMemcpyDeviceToHost)
    (cudaFree d_A d_B d_C)
    (news "cuda xchg finished\n")

    (letrec* ((sumA   (array-sum h_A))
	      (sumB   (array-sum h_B))
	      (sumAB  (+ sumA sumB))
	      (sumC   (array-sum h_C))
	      )
      (news "sumA ~a sumB ~a sumAB ~a sumC ~a\n" sumA sumB sumAB sumC)
      )
    )
  )

(define (cudaTest2)
  (letrec* ((me "cudaTest2")
	    (N (* 10 1024 1024))
	    (h_A (make-float32-vector N))
	    (h_B (make-float32-vector N))

	    (Nbytes (* N (sizeof 1.0)))
	    (d_A (cudaMalloc Nbytes))
	    (d_B (cudaMalloc Nbytes))
	    (stream1 (cudaStreamCreate))
	    (stream2 (cudaStreamCreate))
	    )
    (cudaMemcpy d_A (array-data h_A) Nbytes 'cudaMemcpyHostToDevice stream1)

    (cudaMemcpy d_B (array-data h_B) Nbytes 'cudaMemcpyHostToDevice stream2)
    (cudaFree d_A d_B)
    )
  )

(if have-Cuda (cudaStart)
    (let ((fvoid (lambda x #f))
	  )
      (set! cudaStart fvoid)
      )
    )

